# Generated by Django 6.0.5 on 2026-06-07 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenhouse_app', '0003_greenhouse_total_area_m2'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. NPK 20-20-20, Chlorpyrifos, Tomato Seeds F1', max_length=200)),
                ('category', models.CharField(choices=[('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('seed', 'Seed'), ('tool', 'Tool'), ('packaging', 'Packaging'), ('produce', 'Harvested Produce'), ('other', 'Other')], db_index=True, max_length=20)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Litre (L)'), ('ml', 'Millilitre (mL)'), ('piece', 'Piece / Unit'), ('box', 'Box'), ('bag', 'Bag'), ('other', 'Other')], max_length=10)),
                ('brand', models.CharField(blank=True, default='', help_text='Brand or manufacturer name', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('min_stock_threshold', models.DecimalField(blank=True, decimal_places=3, help_text='Alert when stock falls below this level', max_digits=10, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit in local currency — updated on each purchase', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='greenhouse_app.greenhouse')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_items',
                'ordering': ['category', 'name'],
                'unique_together': {('greenhouse', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('consumption', 'Consumption'), ('harvest', 'Harvest'), ('adjustment_in', 'Adjustment (In)'), ('adjustment_out', 'Adjustment (Out)'), ('waste', 'Waste / Loss')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Always positive — direction is determined by transaction_type', max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit for this transaction', max_digits=12, null=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('performed_at', models.DateField(db_index=True, help_text='Date the transaction occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
                ('operation', models.ForeignKey(blank=True, help_text='Operation that triggered this transaction (consumption/harvest)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='operations.operation')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'db_table': 'inventory_transactions',
                'ordering': ['-performed_at', '-created_at'],
                'indexes': [models.Index(fields=['performed_at', 'transaction_type'], name='inventory_t_perform_c6c2de_idx'), models.Index(fields=['item', 'performed_at'], name='inventory_t_item_id_18fcf7_idx')],
            },
        ),
    ]
