# Generated by Django 6.0.5 on 2026-06-09 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenhouse_app', '0003_greenhouse_total_area_m2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('model_version', models.CharField(blank=True, default='', help_text='Version of the ML model that processed this request', max_length=100)),
                ('ml_error', models.TextField(blank=True, default='', help_text='Error message if ML service failed')),
                ('inference_time_ms', models.PositiveIntegerField(blank=True, help_text='Time taken by ML service in milliseconds', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Farmer observations about the symptoms')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(blank=True, help_text='Specific bed the photos were taken from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_requests', to='greenhouse_app.bed')),
                ('crop', models.ForeignKey(blank=True, help_text='Active crop at the time of diagnosis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_requests', to='greenhouse_app.crop')),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_requests', to='greenhouse_app.greenhouse')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnosis Request',
                'verbose_name_plural': 'Diagnosis Requests',
                'db_table': 'diagnosis_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded plant photo', upload_to='diagnosis/images/%Y/%m/')),
                ('plant_part', models.CharField(choices=[('leaf', 'Leaf'), ('stem', 'Stem'), ('fruit', 'Fruit'), ('root', 'Root'), ('whole', 'Whole plant'), ('other', 'Other')], default='leaf', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diagnosis.diagnosisrequest')),
            ],
            options={
                'verbose_name': 'Diagnosis Image',
                'verbose_name_plural': 'Diagnosis Images',
                'db_table': 'diagnosis_images',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_label', models.CharField(help_text='Raw PlantVillage label, e.g. Tomato___Early_blight', max_length=200)),
                ('disease_name', models.CharField(help_text='Human-readable English name', max_length=200)),
                ('disease_name_fa', models.CharField(blank=True, default='', help_text='Human-readable Farsi name', max_length=200)),
                ('confidence', models.FloatField(help_text='Model confidence 0.0-1.0')),
                ('cause', models.TextField(blank=True, default='')),
                ('remedies', models.JSONField(default=list, help_text='List of treatment recommendations')),
                ('recommended_pesticides', models.JSONField(default=list, help_text='List of pesticides with name, active_ingredient, dose')),
                ('farmer_feedback', models.CharField(choices=[('pending', 'Not yet reviewed'), ('confirmed', 'Farmer confirmed this diagnosis'), ('rejected', 'Farmer rejected this diagnosis')], db_index=True, default='pending', max_length=20)),
                ('farmer_notes', models.TextField(blank=True, default='', help_text='What the farmer says was actually wrong')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='diagnosis.diagnosisrequest')),
            ],
            options={
                'verbose_name': 'Diagnosis Result',
                'verbose_name_plural': 'Diagnosis Results',
                'db_table': 'diagnosis_results',
                'ordering': ['-confidence'],
            },
        ),
        migrations.AddIndex(
            model_name='diagnosisrequest',
            index=models.Index(fields=['greenhouse', 'created_at'], name='diagnosis_r_greenho_a62754_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosisrequest',
            index=models.Index(fields=['status', 'created_at'], name='diagnosis_r_status_190992_idx'),
        ),
    ]
