# Generated by Django 6.0.5 on 2026-06-12 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('greenhouse_app', '0003_greenhouse_total_area_m2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_label', models.CharField(db_index=True, help_text='Raw PlantVillage label, e.g. Tomato___Early_blight', max_length=200, unique=True)),
                ('name_en', models.CharField(help_text='English display name', max_length=200)),
                ('name_fa', models.CharField(blank=True, default='', help_text='Farsi display name', max_length=200)),
                ('cause', models.TextField(blank=True, default='', help_text='What causes this disease')),
                ('remedies', models.JSONField(default=list, help_text='List of treatment recommendation strings')),
                ('recommended_pesticides', models.JSONField(default=list, help_text='List of {name, active_ingredient, dose} dicts')),
                ('source', models.CharField(choices=[('static', 'Static (seeded)'), ('openai', 'Auto-generated (OpenAI)'), ('admin', 'Manual (Admin)')], db_index=True, default='openai', max_length=10)),
                ('confirmed_count', models.PositiveIntegerField(default=0, help_text='Number of times farmers confirmed this diagnosis')),
                ('rejected_count', models.PositiveIntegerField(default=0, help_text='Number of times farmers rejected this diagnosis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disease Knowledge Entry',
                'verbose_name_plural': 'Disease Knowledge Base',
                'db_table': 'disease_knowledge',
                'ordering': ['disease_label'],
            },
        ),
        migrations.AlterField(
            model_name='diagnosisimage',
            name='image',
            field=models.ImageField(upload_to='diagnosis/images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_requests', to='greenhouse_app.bed'),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_requests', to='greenhouse_app.crop'),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='inference_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='ml_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='disease_name',
            field=models.CharField(help_text='Human-readable English name from ML service', max_length=200),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='disease_name_fa',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='farmer_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='recommended_pesticides',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='remedies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='knowledge',
            field=models.ForeignKey(blank=True, help_text='Knowledge base entry for this disease', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_results', to='diagnosis.diseaseknowledge'),
        ),
    ]
