# Generated by Django 6.0.5 on 2026-06-07 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenhouse_app', '0003_greenhouse_total_area_m2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Rent / Land'), ('utilities', 'Utilities (Water, Electricity, Gas)'), ('labour', 'Labour / Wages'), ('equipment', 'Equipment & Maintenance'), ('transport', 'Transport & Logistics'), ('insurance', 'Insurance'), ('marketing', 'Marketing & Sales'), ('admin', 'Administrative & Office'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.CharField(help_text='What this expense was for', max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount in local currency', max_digits=12)),
                ('expense_date', models.DateField(db_index=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='greenhouse_app.greenhouse')),
                ('house', models.ForeignKey(blank=True, help_text='Optionally attribute this expense to a specific hall/section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='greenhouse_app.house')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date', 'category'], name='expenses_expense_6ed541_idx'), models.Index(fields=['greenhouse', 'expense_date'], name='expenses_greenho_23814a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(help_text='Name of buyer / company / market', max_length=200)),
                ('buyer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('product_name', models.CharField(help_text='e.g. Cherry Tomato Grade A', max_length=200)),
                ('quantity_kg', models.DecimalField(decimal_places=3, help_text='Weight sold in kilograms', max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='Sale price per kg in local currency', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount actually received so far', max_digits=12)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('sold_at', models.DateField(db_index=True, help_text='Date of sale / delivery')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, help_text='Crop cycle this sale came from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='greenhouse_app.crop')),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='greenhouse_app.greenhouse')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
                'ordering': ['-sold_at', '-created_at'],
                'indexes': [models.Index(fields=['sold_at', 'payment_status'], name='sales_sold_at_e62c8a_idx'), models.Index(fields=['greenhouse', 'sold_at'], name='sales_greenho_542a69_idx')],
            },
        ),
    ]
