# Generated by Django 6.0.5 on 2026-06-04 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('greenhouse_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousemembership',
            name='greenhouse_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='greenhouse_app.greenhouse'),
        ),
        migrations.AddField(
            model_name='greenhousemembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='Which user invited this member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='greenhousemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='greenhousemembership',
            unique_together={('user', 'greenhouse_app')},
        ),
    ]
