# Generated by Django 6.0.5 on 2026-06-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('greenhouse_app', '0002_alter_house_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenhousemembership',
            old_name='greenhouse_app',
            new_name='greenhouse',
        ),
        migrations.AlterUniqueTogether(
            name='greenhousemembership',
            unique_together={('user', 'greenhouse')},
        ),
    ]
