"""
diagnosis/models.py

Stores disease detection requests, results, and the knowledge base.

Models:
  - DiseaseKnowledge  → per-label knowledge: cause, remedies, pesticides
                        replaces the static disease_data.py file.
                        Generated by OpenAI on first encounter of a new label,
                        then cached permanently in DB.
  - DiagnosisRequest  → one diagnosis session
  - DiagnosisImage    → each uploaded image
  - DiagnosisResult   → each disease found, linked to DiseaseKnowledge
"""

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class DiseaseKnowledge(models.Model):
    """
    Knowledge base entry for one PlantVillage disease label.

    One row per unique label (e.g. "Tomato___Early_blight").
    Created automatically by OpenAI when a new label is encountered.
    Can be edited by admin to improve quality over time.

    Source tracks where the entry came from:
      static   — seeded from disease_data.py at startup
      openai   — generated by gpt-4o-mini automatically
      admin    — manually written or edited by a staff user
    """

    class Source(models.TextChoices):
        STATIC = 'static', _('Static (seeded)')
        OPENAI = 'openai', _('Auto-generated (OpenAI)')
        ADMIN  = 'admin',  _('Manual (Admin)')

    # The raw PlantVillage label — unique key for lookups
    disease_label = models.CharField(
        max_length=200,
        unique=True,
        db_index=True,
        help_text=_('Raw PlantVillage label, e.g. Tomato___Early_blight'),
    )

    # Human-readable names
    name_en = models.CharField(
        max_length=200,
        help_text=_('English display name'),
    )
    name_fa = models.CharField(
        max_length=200,
        blank=True,
        default='',
        help_text=_('Farsi display name'),
    )

    # Knowledge content
    cause = models.TextField(
        blank=True,
        default='',
        help_text=_('What causes this disease'),
    )
    remedies = models.JSONField(
        default=list,
        help_text=_('List of treatment recommendation strings'),
    )
    recommended_pesticides = models.JSONField(
        default=list,
        help_text=_('List of {name, active_ingredient, dose} dicts'),
    )

    # Metadata
    source = models.CharField(
        max_length=10,
        choices=Source.choices,
        default=Source.OPENAI,
        db_index=True,
    )
    # Tracks how many times this label has been confirmed by farmers
    confirmed_count = models.PositiveIntegerField(
        default=0,
        help_text=_('Number of times farmers confirmed this diagnosis'),
    )
    # Tracks how many times this label has been rejected by farmers
    rejected_count = models.PositiveIntegerField(
        default=0,
        help_text=_('Number of times farmers rejected this diagnosis'),
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'disease_knowledge'
        verbose_name = _('Disease Knowledge Entry')
        verbose_name_plural = _('Disease Knowledge Base')
        ordering = ['disease_label']

    def __str__(self):
        return f'{self.name_en} [{self.disease_label}] ({self.get_source_display()})'

    @property
    def accuracy_rate(self):
        """Percentage of farmer confirmations vs total feedback."""
        total = self.confirmed_count + self.rejected_count
        if total == 0:
            return None
        return round(self.confirmed_count / total * 100, 1)


class DiagnosisRequest(models.Model):
    """
    One disease detection session.
    A farmer uploads 1-5 images of a plant showing symptoms.
    """

    class Status(models.TextChoices):
        PENDING    = 'pending',    _('Pending')
        PROCESSING = 'processing', _('Processing')
        COMPLETED  = 'completed',  _('Completed')
        FAILED     = 'failed',     _('Failed')

    submitted_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='diagnosis_requests',
    )
    greenhouse = models.ForeignKey(
        'greenhouse_app.Greenhouse',
        on_delete=models.CASCADE,
        related_name='diagnosis_requests',
    )
    bed = models.ForeignKey(
        'greenhouse_app.Bed',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='diagnosis_requests',
    )
    crop = models.ForeignKey(
        'greenhouse_app.Crop',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='diagnosis_requests',
    )

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
        db_index=True,
    )
    model_version = models.CharField(max_length=100, blank=True, default='')
    ml_error = models.TextField(blank=True, default='')
    inference_time_ms = models.PositiveIntegerField(null=True, blank=True)
    notes = models.TextField(blank=True, default='')

    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'diagnosis_requests'
        verbose_name = _('Diagnosis Request')
        verbose_name_plural = _('Diagnosis Requests')
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['greenhouse', 'created_at']),
            models.Index(fields=['status', 'created_at']),
        ]

    def __str__(self):
        return f'Diagnosis #{self.id} — {self.greenhouse.name} ({self.status})'


class DiagnosisImage(models.Model):

    class PlantPart(models.TextChoices):
        LEAF  = 'leaf',  _('Leaf')
        STEM  = 'stem',  _('Stem')
        FRUIT = 'fruit', _('Fruit')
        ROOT  = 'root',  _('Root')
        WHOLE = 'whole', _('Whole plant')
        OTHER = 'other', _('Other')

    request = models.ForeignKey(
        DiagnosisRequest,
        on_delete=models.CASCADE,
        related_name='images',
    )
    image = models.ImageField(upload_to='diagnosis/images/%Y/%m/')
    plant_part = models.CharField(
        max_length=20,
        choices=PlantPart.choices,
        default=PlantPart.LEAF,
    )
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'diagnosis_images'
        verbose_name = _('Diagnosis Image')
        verbose_name_plural = _('Diagnosis Images')

    def __str__(self):
        return f'Image #{self.id} for request #{self.request_id}'


class DiagnosisResult(models.Model):

    class FarmerFeedback(models.TextChoices):
        PENDING   = 'pending',   _('Not yet reviewed')
        CONFIRMED = 'confirmed', _('Farmer confirmed this diagnosis')
        REJECTED  = 'rejected',  _('Farmer rejected this diagnosis')

    request = models.ForeignKey(
        DiagnosisRequest,
        on_delete=models.CASCADE,
        related_name='results',
    )

    # Link to the knowledge base entry — populated after knowledge generation
    knowledge = models.ForeignKey(
        DiseaseKnowledge,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='diagnosis_results',
        help_text=_('Knowledge base entry for this disease'),
    )

    # Raw ML output — always stored independently of the knowledge base
    disease_label = models.CharField(
        max_length=200,
        help_text=_('Raw PlantVillage label, e.g. Tomato___Early_blight'),
    )
    disease_name = models.CharField(
        max_length=200,
        help_text=_('Human-readable English name from ML service'),
    )
    disease_name_fa = models.CharField(
        max_length=200,
        blank=True,
        default='',
    )
    confidence = models.FloatField()

    # Snapshot of knowledge at time of diagnosis — stored for immutability
    # (so editing the knowledge base doesn't change past diagnoses)
    cause = models.TextField(blank=True, default='')
    remedies = models.JSONField(default=list)
    recommended_pesticides = models.JSONField(default=list)

    # Farmer feedback
    farmer_feedback = models.CharField(
        max_length=20,
        choices=FarmerFeedback.choices,
        default=FarmerFeedback.PENDING,
        db_index=True,
    )
    farmer_notes = models.TextField(blank=True, default='')

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'diagnosis_results'
        verbose_name = _('Diagnosis Result')
        verbose_name_plural = _('Diagnosis Results')
        ordering = ['-confidence']

    def __str__(self):
        return f'{self.disease_name} ({self.confidence:.0%}) for request #{self.request_id}'