# Generated by Django 6.0.5 on 2026-06-04 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short identifier, e.g. 'B-01', 'Row-3'", max_length=50)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Max number of plants this bed holds.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['house', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(help_text="Type of crop. E.g. 'Tomato', 'Cucumber', 'گوجه فرنگی'", max_length=100)),
                ('variety', models.CharField(blank=True, help_text="Specific variety/cultivar. E.g. 'Cherry 100F1', 'Superstar'", max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('planted_at', models.DateField(blank=True, help_text='Actual planting date.', null=True)),
                ('expected_harvest_at', models.DateField(blank=True, help_text='Estimated harvest date, calculated from planting + crop cycle length.', null=True)),
                ('actual_harvest_at', models.DateField(blank=True, help_text='Filled when status → HARVESTED.', null=True)),
                ('plant_count', models.PositiveIntegerField(blank=True, help_text='Number of plants in this crop cycle.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='greenhouse_app.bed')),
            ],
            options={
                'ordering': ['-planted_at'],
            },
        ),
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location_geojson', models.TextField(blank=True, help_text='GeoJSON point string. Example: {"type":"Point","coordinates":[51.38,35.68]}')),
                ('timezone', models.CharField(default='Asia/Tehran', help_text='Timezone for date/time calculations. E.g. Asia/Tehran', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_greenhouses_app', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g. 'Hall A', 'North Section', 'سالن ۱'", max_length=100)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, help_text='Floor area in square meters.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('greenhouse_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='greenhouse_app.greenhouse')),
            ],
            options={
                'ordering': ['greenhouse_app', 'name'],
                'unique_together': {('greenhouse_app', 'name')},
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='greenhouse_app.house'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('house', 'code')},
        ),
    ]
