# Generated by Django 6.0.5 on 2026-06-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['greenhouse', 'name']},
        ),
        migrations.RenameField(
            model_name='house',
            old_name='greenhouse_app',
            new_name='greenhouse',
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('greenhouse', 'name')},
        ),
    ]
