# Generated by Django 6.0.5 on 2026-06-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_app', '0002_alter_house_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='total_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total greenhouse area in square metres', max_digits=10, null=True),
        ),
    ]
