# Generated by Django 6.0.5 on 2026-06-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_app', '0003_greenhouse_total_area_m2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='مساحت به متر مربع'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='حداکثر تعداد گیاهی که این بستر در خود جای می\u200cدهد.', null=True, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='code',
            field=models.CharField(help_text="شناسه کوتاه، برای مثال: 'B-01'، 'Row-3'", max_length=50, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='actual_harvest_at',
            field=models.DateField(blank=True, help_text='زمانی که وضعیت به «برداشت\u200cشده» تغییر کند،تکمیل می\u200cگردد.', null=True, verbose_name='تاریخ برداشت'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_type',
            field=models.CharField(help_text='نوع محصول. برای مثال: «Tomato» (گوجه\u200cفرنگی)، «Cucumber» (خیار)، «گوجه فرنگی»', max_length=100, verbose_name='نوع محصول'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='expected_harvest_at',
            field=models.DateField(blank=True, help_text='تاریخ برداشت تخمینی، محاسبه\u200cشده از زمان کاشت + طول دوره رشد', null=True, verbose_name='تاریخ برداشت تخمینی'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='plant_count',
            field=models.PositiveIntegerField(blank=True, help_text='تعداد گیاهان در این دوره کاشت', null=True, verbose_name='تعداد گیاهان'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='planted_at',
            field=models.DateField(blank=True, help_text='تاریخ دقیق کاشت.', null=True, verbose_name='زمان کاشت'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='status',
            field=models.CharField(choices=[('planned', 'برنامه\u200cریزی شده'), ('growing', 'در حال رشد'), ('harvested', 'برداشت شده'), ('failed', 'ناموفق')], default='planned', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='variety',
            field=models.CharField(blank=True, help_text='گونه/رقم خاص (گیاه). برای مثال: «Cherry 100F1»، «Superstar»', max_length=100, verbose_name='گونه'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است؟'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='location_geojson',
            field=models.TextField(blank=True, help_text='GeoJSON point string. Example: {"type":"Point","coordinates":[51.38,35.68]}', verbose_name='موقعیت مکانی GeoJSON'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='timezone',
            field=models.CharField(default='Asia/Tehran', help_text='منطقه زمانی برای محاسبات تاریخ و زمان. برای مثال: Asia/Tehran', max_length=60, verbose_name='منطقه زمانی'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='total_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مساحت کل گلخانه به متر مربع', max_digits=10, null=True, verbose_name='مجموع مساحت به متر مربع'),
        ),
        migrations.AlterField(
            model_name='house',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مساحت کف به متر مربع', max_digits=10, null=True, verbose_name='مساحت به متر مربع'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(help_text="مانند 'Hall A', 'North Section', 'سالن ۱'", max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='house',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
    ]
