# Generated by Django 6.0.5 on 2026-06-19 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_app', '0004_alter_bed_area_m2_alter_bed_capacity_alter_bed_code_and_more'),
        ('operations', '0002_operation_source_operation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='applied_template',
            field=models.ForeignKey(blank=True, help_text='در صورت اعمال «عملیات پیشنهادی»، قالب استفاده\u200cشده اینجا ثبت می\u200cشود. برای جلوگیری از اعمال دوباره و نمایش وضعیت استفاده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_to_crops', to='operations.cropoperationtemplate', verbose_name='قالب اعمال\u200cشده'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='status',
            field=models.CharField(choices=[('planned', 'کاشته شده'), ('growing', 'در حال رشد'), ('harvested', 'برداشت شده'), ('failed', 'ناموفق')], default='planned', max_length=20, verbose_name='وضعیت'),
        ),
    ]
