# Generated by Django 6.0.5 on 2026-06-19 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_app', '0005_crop_applied_template_alter_crop_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='کاربری که این دوره کاشت را ایجاد کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crops', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
    ]
