# Generated by Django 6.0.5 on 2026-06-06 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenhouse_app', '0003_greenhouse_total_area_m2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('irrigation', 'Irrigation'), ('fertilizing', 'Fertilizing'), ('spraying', 'Spraying'), ('harvesting', 'Harvesting'), ('pruning', 'Pruning'), ('transplant', 'Transplanting'), ('inspection', 'Inspection'), ('other', 'Other')], db_index=True, max_length=30)),
                ('performed_at', models.DateField(db_index=True, help_text='Date the operation actually happened')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Amount used, e.g. 5.0 litres of fertilizer', max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, choices=[('litre', 'Litre (L)'), ('kilogram', 'Kilogram (kg)'), ('gram', 'Gram (g)'), ('piece', 'Piece / Unit'), ('hour', 'Hour'), ('square_m', 'Square Metre (m²)'), ('other', 'Other')], default='', max_length=20)),
                ('product_name', models.CharField(blank=True, default='', help_text='Name of fertilizer, pesticide, or seed used', max_length=200)),
                ('product_batch', models.CharField(blank=True, default='', help_text='Batch or lot number for traceability', max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Direct cost of this operation in local currency', max_digits=12, null=True)),
                ('harvest_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Weight harvested in kg — only for HARVESTING operations', max_digits=10, null=True)),
                ('harvest_quality', models.CharField(blank=True, choices=[('grade_a', 'Grade A'), ('grade_b', 'Grade B'), ('grade_c', 'Grade C'), ('rejected', 'Rejected')], default='', help_text='Quality grade of harvested produce', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Observations, issues, or free-form notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(help_text='Which bed this operation was performed on', on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='greenhouse_app.bed')),
                ('crop', models.ForeignKey(blank=True, help_text='Active crop at the time — auto-linked or manually selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='greenhouse_app.crop')),
                ('logged_by', models.ForeignKey(help_text='User who entered this record (may differ from performer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_logged', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(help_text='Operator who carried out the work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
                'db_table': 'operations',
                'ordering': ['-performed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo of the crop, bed, or issue observed', upload_to='operations/photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='operations.operation')),
            ],
            options={
                'verbose_name': 'Operation Photo',
                'verbose_name_plural': 'Operation Photos',
                'db_table': 'operation_photos',
            },
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['performed_at', 'operation_type'], name='operations_perform_6c8217_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['bed', 'performed_at'], name='operations_bed_id_34f897_idx'),
        ),
    ]
