# Generated by Django 6.0.5 on 2026-06-19 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_app', '0004_alter_bed_area_m2_alter_bed_capacity_alter_bed_code_and_more'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='source',
            field=models.CharField(choices=[('manual', 'دستی'), ('template', 'قالب')], db_index=True, default='manual', help_text='دستی = ثبت مستقیم کاربر، قالب = تولید شده از برنامه پیشنهادی', max_length=20),
        ),
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('planned', 'برنامه\u200cریزی شده'), ('completed', 'انجام شده'), ('skipped', 'رد شده'), ('cancelled', 'لغو شده')], db_index=True, default='completed', help_text='برنامه\u200cریزی\u200cشده = هنوز انجام نشده (از قالب)، انجام\u200cشده = ثبت واقعی، رد شده = این مرحله عمداً انجام نشد، لغو شده = کل برنامه باقی\u200cمانده لغو شد', max_length=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='bed',
            field=models.ForeignKey(help_text='این عمل روی کدام بستر انجام شده است', on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='greenhouse_app.bed'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='هزینه مستقیم این عملیات به پول محلی', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='crop',
            field=models.ForeignKey(blank=True, help_text='محصول فعال در آن زمان - لینک خودکار یا انتخاب دستی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='greenhouse_app.crop'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='harvest_quality',
            field=models.CharField(blank=True, choices=[('grade_a', 'درجه یک'), ('grade_b', 'درجه دو'), ('grade_c', 'درجه سه'), ('rejected', 'رد شده')], default='', help_text='درجه کیفی محصولات برداشت شده', max_length=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='harvest_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='وزن برداشت شده به کیلوگرم — فقط برای عملیات برداشت', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='logged_by',
            field=models.ForeignKey(help_text='کاربری که این رکورد را وارد کرده است (ممکن است با اجراکننده متفاوت باشد)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_logged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='مشاهدات، مسائل یا یادداشت\u200cهای آزاد'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('irrigation', 'آبیاری'), ('fertilizing', 'کود\u200cدهی'), ('spraying', 'سم\u200cپاشی'), ('harvesting', 'برداشت'), ('pruning', 'هرس'), ('transplant', 'نشاء'), ('inspection', 'بازدید'), ('other', 'سایر')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='operation',
            name='performed_at',
            field=models.DateField(db_index=True, help_text='تاریخ انجام عملیات'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='performed_by',
            field=models.ForeignKey(help_text='اپراتوری که کار را انجام داده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='product_batch',
            field=models.CharField(blank=True, default='', help_text='شماره بچ یا لات برای ردیابی', max_length=100),
        ),
        migrations.AlterField(
            model_name='operation',
            name='product_name',
            field=models.CharField(blank=True, default='', help_text='نام کود، آفت\u200cکش یا بذر مورد استفاده', max_length=200),
        ),
        migrations.AlterField(
            model_name='operation',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='مقدار مصرف شده، مثلاً ۵.۰ لیتر کود', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='unit',
            field=models.CharField(blank=True, choices=[('litre', 'لیتر (L)'), ('kilogram', 'کیلوگرم (kg)'), ('gram', 'گرم (g)'), ('piece', 'قطعه / واحد'), ('hour', 'ساعت'), ('square_m', 'متر مربع (m²)'), ('other', 'سایر')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='CropOperationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(db_index=True, help_text='باید دقیقاً با نوع محصول وارد شده در دوره کشت مطابقت داشته باشد. مثال: «گوجه فرنگی»', max_length=100, verbose_name='نوع محصول')),
                ('variety', models.CharField(blank=True, db_index=True, default='', help_text='باید دقیقاً با گونه وارد شده در دوره کشت مطابقت داشته باشد. خالی = برای همه گونه\u200cهای این محصول.', max_length=100, verbose_name='گونه')),
                ('name', models.CharField(help_text='برچسب قابل\u200cخواندن برای مدیریت، مثال: «گوجه گیلاسی — برنامه استاندارد»', max_length=200, verbose_name='نام قالب')),
                ('is_active', models.BooleanField(default=True, help_text='قالب\u200cهای غیرفعال در جستجوی تطبیق نادیده گرفته می\u200cشوند، اما حذف نمی\u200cشوند.', verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('greenhouse', models.ForeignKey(blank=True, help_text='خالی = قالب سراسری (پیش\u200cفرض سیستم). در غیر این صورت فقط برای این گلخانه استفاده می\u200cشود و جایگزین قالب سراسری می\u200cگردد.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_operation_templates', to='greenhouse_app.greenhouse', verbose_name='گلخانه (اختصاصی)')),
            ],
            options={
                'verbose_name': 'قالب عملیات پیشنهادی',
                'verbose_name_plural': 'قالب\u200cهای عملیات پیشنهادی',
                'db_table': 'crop_operation_templates',
                'ordering': ['crop_type', 'variety', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CropOperationTemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('irrigation', 'آبیاری'), ('fertilizing', 'کود\u200cدهی'), ('spraying', 'سم\u200cپاشی'), ('harvesting', 'برداشت'), ('pruning', 'هرس'), ('transplant', 'نشاء'), ('inspection', 'بازدید'), ('other', 'سایر')], max_length=30, verbose_name='نوع عملیات')),
                ('day_offset_start', models.PositiveIntegerField(help_text='روز شروع نسبت به تاریخ کاشت (روز ۱ = روز کاشت).', verbose_name='روز شروع')),
                ('repeat_every_days', models.PositiveIntegerField(blank=True, help_text='خالی = این مرحله فقط یک\u200cبار در «روز شروع» اجرا می\u200cشود. عدد = تکرار هر N روز.', null=True, verbose_name='تکرار هر (روز)')),
                ('repeat_until_day', models.PositiveIntegerField(blank=True, help_text='فقط در صورت تنظیم «تکرار هر»، الزامی است — آخرین روزی که این قانون عملیات تولید می\u200cکند.', null=True, verbose_name='تکرار تا روز')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='مقدار پیش\u200cفرض')),
                ('unit', models.CharField(blank=True, choices=[('litre', 'لیتر (L)'), ('kilogram', 'کیلوگرم (kg)'), ('gram', 'گرم (g)'), ('piece', 'قطعه / واحد'), ('hour', 'ساعت'), ('square_m', 'متر مربع (m²)'), ('other', 'سایر')], default='', max_length=20, verbose_name='واحد پیش\u200cفرض')),
                ('product_name', models.CharField(blank=True, default='', max_length=200, verbose_name='نام محصول/نهاده پیش\u200cفرض')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت پیش\u200cفرض')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='operations.cropoperationtemplate')),
            ],
            options={
                'verbose_name': 'مرحله قالب عملیات',
                'verbose_name_plural': 'مراحل قالب عملیات',
                'db_table': 'crop_operation_template_steps',
                'ordering': ['template', 'day_offset_start'],
            },
        ),
        migrations.AddIndex(
            model_name='cropoperationtemplate',
            index=models.Index(fields=['crop_type', 'variety', 'greenhouse'], name='crop_operat_crop_ty_c90317_idx'),
        ),
    ]
