# Generated by Django 6.0.5 on 2026-06-19 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_app', '0005_crop_applied_template_alter_crop_status'),
        ('operations', '0002_operation_source_operation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['crop', 'status'], name='operations_crop_id_dc307a_idx'),
        ),
    ]
