"""
operations/models.py

The Operations app records every daily field action performed on a bed.
This is the core activity log of the platform — the document calls it
"یکپارچه‌سازی مدیریت عملیات، مالی و فروش" (unified operations management).

Every operation is tied to a Bed (the smallest physical unit) and has:
  - a type (irrigation, fertilizing, spraying, harvesting, etc.)
  - quantities and units
  - the operator who logged it
  - optional notes and photos

Operation types from the business document:
  IRRIGATION   — آبیاری
  FERTILIZING  — کود‌دهی
  SPRAYING     — سم‌پاشی
  HARVESTING   — برداشت
  PRUNING      — هرس
  TRANSPLANT   — نشاء
  INSPECTION   — بازدید / بررسی
  OTHER        — سایر

The document also specifies that operations feed into:
  - Financial reports (cost per operation)
  - AI analysis (pattern detection, disease correlation)
  - Harvest yield tracking

Design decisions:
  - One Operation = one action on one bed on one date
  - quantity + unit captures how much was used (e.g. 5 litres of fertilizer)
  - cost captures the direct cost of this operation (labour + materials)
  - OperationPhoto allows multiple photos per operation (for disease detection)
"""

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class Operation(models.Model):

    class Type(models.TextChoices):
        IRRIGATION  = 'irrigation',  _('آبیاری')       # آبیاری
        FERTILIZING = 'fertilizing', _('کود‌دهی')      # کود‌دهی
        SPRAYING    = 'spraying',    _('سم‌پاشی')          # سم‌پاشی
        HARVESTING  = 'harvesting',  _('برداشت')        # برداشت
        PRUNING     = 'pruning',     _('هرس')           # هرس
        TRANSPLANT  = 'transplant',  _('نشاء')     # نشاء
        INSPECTION  = 'inspection',  _('بازدید')        # بازدید
        OTHER       = 'other',       _('سایر')             # سایر

    class Unit(models.TextChoices):
        LITRE      = 'litre',      _('لیتر (L)')
        KILOGRAM   = 'kilogram',   _('کیلوگرم (kg)')
        GRAM       = 'gram',       _('گرم (g)')
        PIECE      = 'piece',      _('قطعه / واحد')
        HOUR       = 'hour',       _('ساعت')
        SQUARE_M   = 'square_m',   _('متر مربع (m²)')
        OTHER      = 'other',      _('سایر')
    
    class Status(models.TextChoices):
        PLANNED   = 'planned',   _('برنامه‌ریزی شده')   # suggested by a template, not yet done
        COMPLETED = 'completed', _('انجام شده')          # the default for manually-logged ops
        SKIPPED   = 'skipped',   _('رد شده')             # this specific step was intentionally not done
        CANCELLED = 'cancelled', _('لغو شده')            # bulk-cancelled because the rest of the plan is void

    class Source(models.TextChoices):
        MANUAL   = 'manual',   _('دستی')      # logged directly by a user
        TEMPLATE = 'template', _('قالب')      # generated by "Apply suggested operations"

    # ── Core relations ───────────────────────────────────────────────
    bed = models.ForeignKey(
        'greenhouse_app.Bed',
        on_delete=models.CASCADE,
        related_name='operations',
        help_text=_('این عمل روی کدام بستر انجام شده است'),
    )
    crop = models.ForeignKey(
        'greenhouse_app.Crop',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='operations',
        help_text=_('محصول فعال در آن زمان - لینک خودکار یا انتخاب دستی'),
    )
    performed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='operations_performed',
        help_text=_('اپراتوری که کار را انجام داده است'),
    )
    logged_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='operations_logged',
        help_text=_('کاربری که این رکورد را وارد کرده است (ممکن است با اجراکننده متفاوت باشد)'),
    )

    # ── What was done ────────────────────────────────────────────────
    operation_type = models.CharField(
        max_length=30,
        choices=Type.choices,
        db_index=True,
    )
    performed_at = models.DateField(
        help_text=_('تاریخ انجام عملیات'),
        db_index=True,
    )

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.COMPLETED,
        db_index=True,
        help_text=_(
            'برنامه‌ریزی‌شده = هنوز انجام نشده (از قالب)، '
            'انجام‌شده = ثبت واقعی، '
            'رد شده = این مرحله عمداً انجام نشد، '
            'لغو شده = کل برنامه باقی‌مانده لغو شد'
        ),
    )
    source = models.CharField(
        max_length=20,
        choices=Source.choices,
        default=Source.MANUAL,
        db_index=True,
        help_text=_('دستی = ثبت مستقیم کاربر، قالب = تولید شده از برنامه پیشنهادی'),
    )

    # ── Quantity ─────────────────────────────────────────────────────
    quantity = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        null=True,
        blank=True,
        help_text=_('مقدار مصرف شده، مثلاً ۵.۰ لیتر کود'),
    )
    unit = models.CharField(
        max_length=20,
        choices=Unit.choices,
        blank=True,
        default='',
    )

    # ── Product / Material ───────────────────────────────────────────
    product_name = models.CharField(
        max_length=200,
        blank=True,
        default='',
        help_text=_('نام کود، آفت‌کش یا بذر مورد استفاده'),
    )
    product_batch = models.CharField(
        max_length=100,
        blank=True,
        default='',
        help_text=_('شماره بچ یا لات برای ردیابی'),
    )

    # ── Financials ───────────────────────────────────────────────────
    cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text=_('هزینه مستقیم این عملیات به پول محلی'),
    )

    # ── Harvest specific ─────────────────────────────────────────────
    harvest_weight_kg = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        null=True,
        blank=True,
        help_text=_('وزن برداشت شده به کیلوگرم — فقط برای عملیات برداشت'),
    )
    harvest_quality = models.CharField(
        max_length=20,
        blank=True,
        default='',
        choices=[
            ('grade_a', _('درجه یک')),
            ('grade_b', _('درجه دو')),
            ('grade_c', _('درجه سه')),
            ('rejected', _('رد شده')),
        ],
        help_text=_('درجه کیفی محصولات برداشت شده'),
    )

    # ── Notes ────────────────────────────────────────────────────────
    notes = models.TextField(
        blank=True,
        default='',
        help_text=_('مشاهدات، مسائل یا یادداشت‌های آزاد'),
    )

    # ── Timestamps ───────────────────────────────────────────────────
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'operations'
        verbose_name = _('Operation')
        verbose_name_plural = _('Operations')
        ordering = ['-performed_at', '-created_at']
        indexes = [
            models.Index(fields=['performed_at', 'operation_type']),
            models.Index(fields=['bed', 'performed_at']),
            models.Index(fields=['crop', 'status']),
        ]

    def __str__(self):
        import jdatetime
        try:
            jalali = jdatetime.date.fromgregorian(date=self.performed_at)
            date_str = jalali.strftime('%Y/%m/%d')
        except Exception:
            date_str = str(self.performed_at)
        return (
            f'{self.get_operation_type_display()} '
            f'@ {self.bed} '
            f'در {date_str}'
        )

    @property
    def greenhouse(self):
        return self.bed.house.greenhouse


class OperationPhoto(models.Model):
    """
    One or more photos attached to an operation.
    Primary use: disease detection (Module 3 — AI image analysis).
    Photos are uploaded per-operation and later sent to the
    FastAPI ML inference service.
    """
    operation = models.ForeignKey(
        Operation,
        on_delete=models.CASCADE,
        related_name='photos',
    )
    image = models.ImageField(
        upload_to='operations/photos/%Y/%m/',
        help_text=_('Photo of the crop, bed, or issue observed'),
    )
    caption = models.CharField(
        max_length=200,
        blank=True,
        default='',
    )
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'operation_photos'
        verbose_name = _('Operation Photo')
        verbose_name_plural = _('Operation Photos')

    def __str__(self):
        return f'Photo for {self.operation} ({self.uploaded_at.date()})'



class CropOperationTemplate(models.Model):
    """
    A reusable, pre-defined schedule of operations for a given crop_type +
    variety combination. When a user clicks "Add suggested operations" on a
    growing Crop, the system looks up the matching template, expands its
    steps into real Operation rows (status=PLANNED, source=TEMPLATE), and
    records the link on Crop.applied_template.

    Scoping:
      - greenhouse = NULL  → global/system default template, usable by
        every greenhouse on the platform.
      - greenhouse = <X>   → an override specific to greenhouse X. If a
        greenhouse-specific template exists for a given (crop_type, variety),
        it is used INSTEAD of the global one — never merged with it. To
        customize, clone the global template's steps into a new
        greenhouse-scoped template and edit from there.

    Matching is done on (crop_type, variety) as plain strings, mirroring
    how Crop.crop_type / Crop.variety are already stored (free text, not FK)
    elsewhere in the system.

    Entered directly via Django admin for now (no import/seed file flow yet).
    """

    crop_type = models.CharField(
        max_length=100,
        db_index=True,
        help_text=_('باید دقیقاً با نوع محصول وارد شده در دوره کشت مطابقت داشته باشد. مثال: «گوجه فرنگی»'),
        verbose_name=_('نوع محصول'),
    )
    variety = models.CharField(
        max_length=100,
        blank=True,
        default='',
        db_index=True,
        help_text=_('باید دقیقاً با گونه وارد شده در دوره کشت مطابقت داشته باشد. خالی = برای همه گونه‌های این محصول.'),
        verbose_name=_('گونه'),
    )
    greenhouse = models.ForeignKey(
        'greenhouse_app.Greenhouse',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='crop_operation_templates',
        help_text=_('خالی = قالب سراسری (پیش‌فرض سیستم). در غیر این صورت فقط برای این گلخانه استفاده می‌شود و جایگزین قالب سراسری می‌گردد.'),
        verbose_name=_('گلخانه (اختصاصی)'),
    )
    name = models.CharField(
        max_length=200,
        help_text=_('برچسب قابل‌خواندن برای مدیریت، مثال: «گوجه گیلاسی — برنامه استاندارد»'),
        verbose_name=_('نام قالب'),
    )
    is_active = models.BooleanField(
        default=True,
        help_text=_('قالب‌های غیرفعال در جستجوی تطبیق نادیده گرفته می‌شوند، اما حذف نمی‌شوند.'),
        verbose_name=_('فعال است؟'),
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'crop_operation_templates'
        verbose_name = _('قالب عملیات پیشنهادی')
        verbose_name_plural = _('قالب‌های عملیات پیشنهادی')
        ordering = ['crop_type', 'variety', 'name']
        indexes = [
            models.Index(fields=['crop_type', 'variety', 'greenhouse']),
        ]

    def __str__(self):
        scope = self.greenhouse.name if self.greenhouse_id else 'سراسری'
        variety_part = f' ({self.variety})' if self.variety else ''
        return f'{self.crop_type}{variety_part} — {self.name} [{scope}]'


class CropOperationTemplateStep(models.Model):
    """
    One rule within a CropOperationTemplate. Each step is either:

      - ONE-OFF: repeat_every_days is null. Generates exactly one Operation,
        on day `day_offset_start` relative to Crop.planted_at.

      - RECURRING: repeat_every_days is set. Generates one Operation every
        N days, starting at `day_offset_start` and continuing up to and
        including `repeat_until_day` (also relative to planted_at).

    Multiple steps with the same operation_type are expected and normal —
    e.g. two separate "irrigation" rows to express a cadence that changes
    partway through the crop cycle (water every 2 days for 30 days, then
    every 4 days after that).

    quantity / unit / product_name / notes are optional starting defaults
    copied onto each generated Operation — the user can edit any of them
    afterward. `cost` is intentionally NOT included here: generated
    Operations always start with cost=None, filled in later by whoever
    completes the operation.
    """

    template = models.ForeignKey(
        CropOperationTemplate,
        on_delete=models.CASCADE,
        related_name='steps',
    )

    operation_type = models.CharField(
        max_length=30,
        choices=Operation.Type.choices,
        verbose_name=_('نوع عملیات'),
    )

    day_offset_start = models.PositiveIntegerField(
        help_text=_('روز شروع نسبت به تاریخ کاشت (روز ۱ = روز کاشت).'),
        verbose_name=_('روز شروع'),
    )
    repeat_every_days = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text=_('خالی = این مرحله فقط یک‌بار در «روز شروع» اجرا می‌شود. عدد = تکرار هر N روز.'),
        verbose_name=_('تکرار هر (روز)'),
    )
    repeat_until_day = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text=_('فقط در صورت تنظیم «تکرار هر»، الزامی است — آخرین روزی که این قانون عملیات تولید می‌کند.'),
        verbose_name=_('تکرار تا روز'),
    )

    quantity = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        null=True,
        blank=True,
        verbose_name=_('مقدار پیش‌فرض'),
    )
    unit = models.CharField(
        max_length=20,
        choices=Operation.Unit.choices,
        blank=True,
        default='',
        verbose_name=_('واحد پیش‌فرض'),
    )
    product_name = models.CharField(
        max_length=200,
        blank=True,
        default='',
        verbose_name=_('نام محصول/نهاده پیش‌فرض'),
    )
    notes = models.TextField(
        blank=True,
        default='',
        verbose_name=_('یادداشت پیش‌فرض'),
    )

    class Meta:
        db_table = 'crop_operation_template_steps'
        verbose_name = _('مرحله قالب عملیات')
        verbose_name_plural = _('مراحل قالب عملیات')
        ordering = ['template', 'day_offset_start']

    def __str__(self):
        if self.repeat_every_days:
            return (
                f'{self.get_operation_type_display()} '
                f'(روز {self.day_offset_start}، هر {self.repeat_every_days} روز '
                f'تا روز {self.repeat_until_day})'
            )
        return f'{self.get_operation_type_display()} (روز {self.day_offset_start})'

    def clean(self):
        from django.core.exceptions import ValidationError
        if self.repeat_every_days and not self.repeat_until_day:
            raise ValidationError({
                'repeat_until_day': _('در صورت تنظیم «تکرار هر»، «تکرار تا روز» الزامی است.')
            })
        if self.repeat_until_day and self.repeat_until_day < self.day_offset_start:
            raise ValidationError({
                'repeat_until_day': _('«تکرار تا روز» نمی‌تواند کوچک‌تر از «روز شروع» باشد.')
            })
