version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: greenhouse_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=greenhouse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: greenhouse_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: