# Generated by Django 6.0.5 on 2026-06-18 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenhouse_app', '0004_alter_bed_area_m2_alter_bed_capacity_alter_bed_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, default='', help_text='Username captured at time of action, in case user is later deleted', max_length=150)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], db_index=True, max_length=10)),
                ('entity_type', models.CharField(db_index=True, help_text='Model name, e.g. "Operation", "Sale", "InventoryItem"', max_length=100)),
                ('entity_id', models.PositiveIntegerField(help_text='Primary key of the affected record', null=True)),
                ('entity_label', models.CharField(blank=True, default='', help_text='Human-readable string representation of the record at time of action', max_length=300)),
                ('diff', models.JSONField(blank=True, help_text='For UPDATE: {"field": {"before": old_val, "after": new_val}, ...}. For CREATE: the new values. For DELETE: the final values before deletion.', null=True)),
                ('notes', models.CharField(blank=True, default='', help_text='Optional context added by the signal handler', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('greenhouse', models.ForeignKey(blank=True, help_text='Greenhouse this action belongs to — used for owner/manager filtering', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='greenhouse_app.greenhouse')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['greenhouse', '-timestamp'], name='audit_logs_greenho_715fab_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx')],
            },
        ),
    ]
